# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('cor', models.CharField(choices=[('bl', 'black'), ('bu', 'blue'), ('ye', 'yellow'), ('rd', 'red'), ('gr', 'green')], default='bl', max_length=2)),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=20)),
                ('categ', models.CharField(max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
