# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160803_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='operadora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Operadora'),
            preserve_default=False,
        ),
    ]
