# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contato_operadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='cor',
            field=models.CharField(choices=[('black', 'black'), ('blue', 'blue'), ('yellow', 'yellow'), ('red', 'red'), ('green', 'green')], default='blue', max_length=4),
        ),
    ]
