# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160803_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='serial',
            field=models.CharField(default='0000', max_length=20),
        ),
    ]
